### ISSUE TITLE
Run Operation based on the result of previous operation

### ISSUE THREAD

**Issue by ikwattro** [Tolerance/Tolerance#58]
Hi @sroze ,

I have a use case where I need to insert an element in a database based on a previous condition, for example : 

I have an API endpoint that receives events from a website (GoogleAnalyticsTagManager events).
For the same page load I can receive multiple events with roughly the same data (for example I can receive events when the user is scrolling the page with additional data likes elements shown on his page area).

This endpoint will just dispatch the event data to RabbitMQ.

On the other side I have a RMQ worker, which will read and process the event messages. In the current scenario, I can have 5 or 6 messages in sequence that will represent actions on the same website page. I am only interested in inserting 1 click event in my database.

My current application checks whether the last clicked page id (in the database) is the same as the event data page id, if no, then I write the new click into the database. We are not using Tolerance right now but we are investigating it a lot for a data ingestion platform.

So, the current need is to only perform the `ClickInsert` operation only if the `CheckLastVisitedPropertyIsNotSameAsCurrent` operation returns true.

I'm aware Tolerance doesn't have such OperationRunners right now and I would like to know your advise about this need and your current vision of Tolerance's architecture about this need as we would definitely be happy to contribute back the created runners if you find them generic enough.

I see multiple ways of achieving it, one of them is based on other needs which would need another ticket on this topic.

Plan A)

This would basically be a kind of BufferedOperationRunner where operations have to be run in sequence, however you would be able to pass `PreflightOperations` that should all return true in order to run the normal `Operations`.

Plan B)

There could be a `ChainedOperationRunner` (actually your current ChainOperationRunner doesn't have the meaning I have in mind for chains) where every operation would have to return another `Operation`, something like : 

``` php
$nextOperation = $this->operation;
do {
  $nextOperation = $nextOperation->run();
} while ($nextOperation instanceof Operation);
```

Do you have other ideas in mind ?

Thanks for your thoughts on this and thanks for making this library.

**Comment by sroze** [comment]
Closing as per the pull-request. Hope you were able to solve your problem @ikwattro :)
