### ISSUE TITLE
v0.4.1 requires php 7

### ISSUE THREAD

**Issue by Gregoire-M** [Tolerance/Tolerance#99]
In [this commit](https://github.com/Tolerance/Tolerance/commit/84f89661d0098e114a73919c55e694fa187cd4f5), a `float` type hint has been added. But the `composer.json` files doesn't specify that php 7 is required.

So when I ran `composer update` on my project running on php 5.6, tolerance has been updated (0.4.0 => 0.4.1), and I get this fatal error: `Fatal error: Default value for parameters with a class type hint can only be NULL in /var/www/html/vendor/tolerance/tolerance/src/Tolerance/Waiter/ExponentialBackOff.php on line 41`

So, could you remove the php 7 syntax? Or specify a php 7 requirement in `composer.json`?
Thanks.

**Comment by sroze** [comment]
Ooops. This indeed needs to be reverted.

**Comment by sroze** [comment]
Fixed in #100 and released [0.4.2](https://github.com/Tolerance/Tolerance/releases/tag/0.4.2).

**Comment by Gregoire-M** [comment]
Thanks!
